name: flutter_js
description: A Javascript engine for flutter.
version: 0.1.0
homepage: https://github.com/dolphinxx/flutter_js
repository: https://github.com/dolphinxx/flutter_js

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=1.10.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: "^1.0.0"
  http: ^0.13.1
  sync_http: ^0.3.0
  flutter_js_platform_interface:
    path: ../flutter_js_platform_interface
  flutter_js_linux:
    path: ../flutter_js_linux
  flutter_js_macos:
    path: ../flutter_js_macos
  flutter_js_windows:
    path: ../flutter_js_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.whaleread.flutter_js
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        default_package: flutter_js_linux
      macos:
        default_package: flutter_js_macos
      windows:
        default_package: flutter_js_windows