name: fjs_macos
description: macOS implementation of the fjs plugin.
version: 0.1.0
homepage: https://github.com/dolphinxx/fjs/tree/master/fjs/fjs_macos

flutter:
  plugin:
    implements: fjs
    platforms:
      macos:
        pluginClass: FlutterJsPlugin

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
