name: fjs
description: A Javascript engine for flutter.
version: 0.1.0
homepage: https://github.com/dolphinxx/fjs
repository: https://github.com/dolphinxx/fjs

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=1.10.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: "^1.0.0"
  http: ^0.13.1
  sync_http: ^0.3.0
  fjs_platform_interface:
    path: ../fjs_platform_interface
  fjs_linux:
    path: ../fjs_linux
  fjs_macos:
    path: ../fjs_macos
  fjs_windows:
    path: ../fjs_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.whaleread.fjs
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        default_package: fjs_linux
      macos:
        default_package: fjs_macos
      windows:
        default_package: fjs_windows